name: 
    Terraform CI pipeline for infra deployment

run-name: 
    ${( github.actor )} has triggered the following action

on:
    push:
        branches:
            - 'main'
        


# env: 
#     AWS_ACCESS_KEY_ID: ${( secrets.AWS_ACCESS_KEY )} #this is passes in github as a secret
#     AWS_SECRET_ACCESS_KEY_ID: ${( secrets.AWS_SECRET_KEY )}
    

jobs:
    build-infra:
        name: "Terrafrom infrastructure build"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2 #plugin name

            - name: Terraform Setup
              uses: hashicorp/setup-terraform@v2 #plugin name
            
            #use this insead of assiging environment variables for login credentials
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: ap-south-1


            - name: Terraform initialization
              id : init #to identify within the pipeline script
              run: terraform init #runs the following command on the runner
              working-directory: ./Terraform-VPC #where the command has to be executed
            
            - name: Terraform validation
              id : validate
              run: terraform validate
              working-directory: ./Terraform-VPC

            - name: Terraform planning 
              id : plan
              run: terraform plan
              working-directory: ./Terraform-VPC

            - name: Terraform final deployment
              id : apply
              run: terraform apply --auto-approve
              working-directory: ./Terraform-VPC